# Generated by Django 4.1.7 on 2023-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Reg_Number', models.TextField(unique=True)),
                ('Student_Name', models.TextField()),
                ('Student_Email', models.TextField()),
                ('Stuent_Mobile', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
