# Generated by Django 4.1.5 on 2023-04-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Stuent_Mobile',
            new_name='Student_Mobile',
        ),
    ]
